
image: $CI_REGISTRY/move/software/docker-images/dosis:master

stages:
  - verify
  - check
  - build
  - test
  - doc
  - deploy
  - release

include:
  - local: '.gitlab/no-newline-check.yml'
  # - local: '.gitlab/clang.yml'
