class Va41620Config:
    # Size of Datatypes to calculate Offset.
    POINTER_SIZE = 4
    SIZE_T_SIZE = 4
    UINT32_T_SIZE = 4
    COMPLETE_ALWAYS_KEEP_SIZE = 4
    COMPLETION_STATUS_SIZE = 2
    BOOTLOADER_SIZE = 4 * 1024
    BYTE_ORDER = 'little'
    HMAC_KEY_SIZE = 32
    HMAC_SIGNATURE_SIZE = 32
    METADATA_LABEL_OFFSET = 0x350
    IMAGE_BEGIN_ADDRESSES = [4096, 262144,
                             520192, 778240, 1036288, 1294336, 1552384]

    # Offsets
    HMAC_KEY_OFFSET = METADATA_LABEL_OFFSET + \
        1 * UINT32_T_SIZE + 2 * SIZE_T_SIZE
    FIRST_IMAGE_METADATA_OFFSET = HMAC_KEY_OFFSET + HMAC_KEY_SIZE
    FIRST_CRC_OFFSET = FIRST_IMAGE_METADATA_OFFSET + 1 * UINT32_T_SIZE
    FIRST_LENGTH_OFFSET = FIRST_IMAGE_METADATA_OFFSET + \
        4 * UINT32_T_SIZE + 1 * POINTER_SIZE
    FIRST_COMPLETE_OFFSET = FIRST_IMAGE_METADATA_OFFSET + \
        5 * UINT32_T_SIZE + 1 * POINTER_SIZE
    FIRST_HMAC_OFFSET = FIRST_COMPLETE_OFFSET + COMPLETE_ALWAYS_KEEP_SIZE
    SIZE_OF_IMAGE_METADATA = 5 * UINT32_T_SIZE + 1 * \
        POINTER_SIZE + 1 * COMPLETE_ALWAYS_KEEP_SIZE + HMAC_SIGNATURE_SIZE

    MAX_BINARY_IMAGE_SIZE = IMAGE_BEGIN_ADDRESSES[1] - IMAGE_BEGIN_ADDRESSES[0]


class Va41620_Dev_BoardConfig:
    # Size of Datatypes to calculate Offset.
    POINTER_SIZE = 4
    SIZE_T_SIZE = 4
    UINT32_T_SIZE = 4
    COMPLETE_ALWAYS_KEEP_SIZE = 4
    COMPLETION_STATUS_SIZE = 2
    BOOTLOADER_SIZE = 4 * 1024
    BYTE_ORDER = 'little'
    HMAC_KEY_SIZE = 32
    HMAC_SIGNATURE_SIZE = 32
    METADATA_LABEL_OFFSET = 0x350
    IMAGE_BEGIN_ADDRESSES = [4096, 68608, 133120, 197632]

    # Offsets
    HMAC_KEY_OFFSET = METADATA_LABEL_OFFSET + \
        1 * UINT32_T_SIZE + 2 * SIZE_T_SIZE
    FIRST_IMAGE_METADATA_OFFSET = HMAC_KEY_OFFSET + HMAC_KEY_SIZE
    FIRST_CRC_OFFSET = FIRST_IMAGE_METADATA_OFFSET + 1 * UINT32_T_SIZE
    FIRST_LENGTH_OFFSET = FIRST_IMAGE_METADATA_OFFSET + \
        4 * UINT32_T_SIZE + 1 * POINTER_SIZE
    FIRST_COMPLETE_OFFSET = FIRST_IMAGE_METADATA_OFFSET + \
        5 * UINT32_T_SIZE + 1 * POINTER_SIZE
    FIRST_HMAC_OFFSET = FIRST_COMPLETE_OFFSET + COMPLETE_ALWAYS_KEEP_SIZE
    SIZE_OF_IMAGE_METADATA = 5 * UINT32_T_SIZE + 1 * \
        POINTER_SIZE + 1 * COMPLETE_ALWAYS_KEEP_SIZE + HMAC_SIGNATURE_SIZE

    MAX_BINARY_IMAGE_SIZE = IMAGE_BEGIN_ADDRESSES[1] - IMAGE_BEGIN_ADDRESSES[0]


CONFIG_MAP = {
    "va41620": Va41620Config,
    "va41620_dev_board": Va41620_Dev_BoardConfig}
